### ISSUE TITLE
BUG: Missing default NES and DS skin

### ISSUE THREAD

**Issue by HStephens05** [lonkelle/Deltroid#14] opened 2023-01-22 00:30 UTC
The controller settings are missing its default skins for NES and DS. I am using a 13 Pro Max on iOS 16.2.
![D7A95392-B7EF-4A09-8457-B10E621A34A5](https://user-images.githubusercontent.com/78606100/213895271-e923ea01-fb2b-4831-8ad4-ef73fc03eb25.png)
![8E310AA6-C405-42C6-9423-948FAAED8D59](https://user-images.githubusercontent.com/78606100/213895273-fba77a88-5f91-458b-92a4-f87a684f2c12.png)

**Comment by upal212** [comment] 2023-01-22 08:56
Experienced the same issue on XS running 16.2

**Comment by Jonathon-R-C** [comment] 2023-01-31 12:44
Same issue in ipad air 2 running ios 15.6. Sadly cannot import any skins either and the touch screen in the DS also doesnt seem to work likely as a result of the broken skin.

**Comment by AbnormalPoof** [comment] 2023-02-01 04:47
This is an issue with the melonDS core, DeSmuME works as intended.

**Comment by Jonathon-R-C** [comment] 2023-02-01 13:03
Trying to change cores crashes the app for me

**Comment by lonkelle** [comment] 2023-02-02 12:17
Fixed in latest release.

**Closed as completed by lonkelle** 2023-02-02 12:17 UTC
